language: python

env:
 - DJANGO_VERSION=1.11.8
 - DJANGO_VERSION=2.0

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"

matrix:
  exclude:
  - python: "2.7"
    env: DJANGO_VERSION=2.0
  - python: "pypy"
    env: DJANGO_VERSION=2.0
  - python: "3.7-dev"
    env: DJANGO_VERSION=1.11.8

install:
 - pip install -q Django==$DJANGO_VERSION requests responses mock

script:
 - python runtests.py
